### ISSUE TITLE
"An error occurred" imprecise error message upon deploying overwrite

### ISSUE THREAD

**Issue by TimDaub** [manifoldxyz/royalty-registry-client#13]
<img width="619" alt="Screenshot 2022-06-10 at 14 18 35" src="https://user-images.githubusercontent.com/2758453/173062766-12fc494b-60e2-482c-bf6e-36637a85e3fe.png">

```
Transaction Hash: 0xe096349531a08472f42daa2e116ee29cece68d42116e3364b1f7aed59e7ef2a9Etherscan: https://etherscan.io/tx/0xe096349531a08472f42daa2e116ee29cece68d42116e3364b1f7aed59e7ef2a9Confirming...Confirmed.Contract Address: 0x87148545B9Fe13B4b5a32d1719D3BD9c936D577BEtherscan: https://etherscan.io/address/0x87148545B9Fe13B4b5a32d1719D3BD9c936D577B
An error occured.
```

What should I do now?

Edit: After deleting my cookies, this error resolves and the website now shows a valid state:

<img width="983" alt="Screenshot 2022-06-10 at 14 23 16" src="https://user-images.githubusercontent.com/2758453/173063407-682d68f9-208f-4d42-b785-6d5db1d4b9e5.png">

I saw a third-party cookie issue with pendingTransactionConformation or something. So you should look into that. I'm in Mozilla Firefox Dev edition

**Comment by TimDaub** [comment]
I don't remember. But generally when I see that a UI relies on a tx's state, I'd be cautious to e.g. speed-up because I know of the troubles of tracking txs. So I think I didn't.

**Comment by wwhchung** [comment]
Should be addressed in the latest commit.
