### ISSUE TITLE
For "Token Contract Default Royalty" UI asks for "Basis Points" but this concept isn't sufficiently explained with Example: 10% = 1000 Basis Points.

### ISSUE THREAD

**Issue by TimDaub** [manifoldxyz/royalty-registry-client#14]
<img width="949" alt="Screenshot 2022-06-10 at 14 25 57" src="https://user-images.githubusercontent.com/2758453/173063809-7091fe7b-4eda-4060-a8ea-dd59aa00ed1f.png">

As a user I want to understand why I can't simply set 10% = 1000 Basis Points. If the later statements is indeed reality, then why can't I straight up set percentages? So what is this concept of Basis Points? Where can I look it up? The FAQ makes no mention of the concept.

**Comment by wwhchung** [comment]
A basis point is a standard financial term
https://www.investopedia.com/terms/b/basispoint.asp

**Comment by TimDaub** [comment]
Maybe u should still link to that article on your page. Because I really wasn't aware of that term and tried googling it without any knowledge that it's a common finance term. And since "basis" and "point" are very low context, generic terms the search results are all over the place.
