### ISSUE TITLE
Explain "Royalty Basis Points" range

### ISSUE THREAD

**Issue by evvvritt** [manifoldxyz/royalty-registry-client#4]
Hi, it would be helpful to know that 1000 points means 10%. RBP is not explained in the FAQ and the UI even accepts values higher than 10000.

**Comment by wwhchung** [comment]
It accepts over 10000, but will disable the button (or should disable the button) if you enter a higher value.

**Comment by wwhchung** [comment]
I see the issue, looking at it.

**Comment by wwhchung** [comment]
this has been fixed.
