### ISSUE TITLE
"Access Denied" trying to edit override?

### ISSUE THREAD

**Issue by evvvritt** [manifoldxyz/royalty-registry-client#5]
Hi, the UI froze after testing a RBP over 10000 (to see if it would throw an error in the wallet since the UI didn't convey a maximum) and when I refreshed and added token address it shows an "Access Denied" screen (even with wallet still disconnected and re-connected)
<img width="989" alt="Screen Shot 2022-02-02 at 6 26 17 PM" src="https://user-images.githubusercontent.com/6071219/152205860-6c4c8afd-25eb-45b0-a96d-8ce82bcce8b1.png">

**Comment by wwhchung** [comment]
Cannot reproduce, what address/network/wallet are you trying with?
